import { defaults } from 'jest-config'; 
module.exports = {
  ...defaults,
  preset: 'ts-jest',
  testEnvironment: 'jest-environment-jsdom',
  collectCoverage: true,
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/assets/**',
    '!src/types/**',
    '!<rootDir>/node_modules/',
    '!<rootDir>/src/index.tsx',
    '!<rootDir>/src/reportWebVitals.ts',
  ],
  coverageDirectory: 'coverage',
  transform: {
    "^.+\\.[t|j]sx?$": "babel-jest",
  },
  //coverageReporters: ['text', 'html'],
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "/coverage",
    "package.json",
    "package-lock.json",
    "reportWebVitals.ts",
    "setupTests.ts",
    "/test/__mocks__",
    "<rootDir>/src/contant"
  ],
  setupFilesAfterEnv: ['<rootDir>/setupTests.ts'],
  moduleNameMapper: {
    '^types/(.*)$': '<rootDir>/src/types/$1',
    '^utils/(.*)$': '<rootDir>/src/utils/$1',
    'DataContext': '<rootDir>/src/DataContext',
    '^components/(.*)$': '<rootDir>/src/components/$1',
    '^Motor/(.*)$': '<rootDir>/src/Motor/$1',
    '^claims/(.*)$': '<rootDir>/src/claims/$1',
    '^Home/(.*)$': '<rootDir>/src/Home/$1',
    '^context/(.*)$': '<rootDir>/src/context/$1',
    '^hook/(.*)$': '<rootDir>/src/hook/$1',
    '^constant$': '<rootDir>/src/constant',
    '\\.(css|less|scss)$': 'identity-obj-proxy', 
    '\\.(jpg|jpeg|png|gif|svg|mp4)$': '<rootDir>/__mocks__/fileMock.js',
    '^assets/CommonSVG': '<rootDir>/__mocks__/fileMock.js',
    '^assets/Products/index': '<rootDir>/__mocks__/fileMock.js',
    '^@app-shell/(.*)$': '<rootDir>/../app-shell/src/$1',
  },
};