import {
  WhatsappIcon,
  OrgShuffleEmail,
  OrgShuffleLocation,
  OrgShuffleMessage,
  ChatBoatIcon,
  RaiseRequestIcon,
  IconPhone,
  IconFax,
  IconMail,
  IconMeeting,  
  IconProfile,
  IconPreferences,
  IconLogout,
  IconDefaultUserImg
} from "../assets/Header";
import {
  activeAccidentLiabilityIcon,
  activeDomesticLabourIcon,
  activeEngineeringIcon,
  activeHealthIcon,
  activeHomeOwnersIcon,
  activeMarineIcon,
  activeAviationIcon,
  activeMedicalIcon,
  activeMotorIcon,
  activePaymentIcon,
  activePersonalAccidentIcon,
  activePropertyIcon,
  activeProtectionIcon,
  activeShopInsuranceIcon,
  activeSpecializedIcon,
  activeTransportIcon,
  activeVisitorVisaIcon,
  activeRegisterClaim,
  activeTrackClaim,
  activeClaimsAndClaims,
  activePdfIcon,

  nonactivePersonalAccidentIcon,
  nonactiveDomesticLabourIcon,
  nonactiveHomeOwnersIcon,
  nonactiveMedicalIcon,
  nonactiveMotorIcon, 
  nonactivePropertyIcon,
  nonactiveProtectionIcon,  
  nonactiveTransportIcon, 
  nonactiveVisitorVisaIcon, 
} from "../assets/Header/activeIcons";

interface IconSetProps {
  [key: string]: string;
}

export const IconsSet: IconSetProps = {
  whatsapp: WhatsappIcon,
  chat: ChatBoatIcon,
  raise: RaiseRequestIcon,
  claims: activeClaimsAndClaims,
  email: OrgShuffleEmail,
  branch: OrgShuffleLocation,
  location: OrgShuffleLocation,
  feedback: OrgShuffleMessage,
  track: activeTrackClaim,
  register: activeRegisterClaim,
  motor: activeMotorIcon,
  accident: activeAccidentLiabilityIcon,
  domestic: activeDomesticLabourIcon,
  engineering: activeEngineeringIcon,
  health: activeHealthIcon,
  home: activeHomeOwnersIcon,
  marine: activeMarineIcon,
  aviation: activeAviationIcon,
  medical: activeMedicalIcon,
  medical_mal: activeMedicalIcon,
  payment: activePaymentIcon,
  personal_accident: activePersonalAccidentIcon,
  property: activePropertyIcon,
  protection: activeProtectionIcon,
  shopInsurance: activeShopInsuranceIcon,
  specialized: activeSpecializedIcon,
  travel: activeTransportIcon,
  visitor: activeVisitorVisaIcon,
  pdf: activePdfIcon,
  phone: IconPhone,
  mail: IconMail,
  fax: IconFax,
  meeting: IconMeeting,
  profile:IconProfile,
  preferences:IconPreferences,
  logout:IconLogout,
  default: IconDefaultUserImg,


  nonpersonal_accident: nonactivePersonalAccidentIcon,
  nondomestic: nonactiveDomesticLabourIcon,
  nonhome: nonactiveHomeOwnersIcon,
  nonmedical: nonactiveMedicalIcon,
  nonmotor: nonactiveMotorIcon, 
  nonproperty: nonactivePropertyIcon,
  nonprotection: nonactiveProtectionIcon, 
  nontravel: nonactiveTransportIcon,
  nonvisitor: nonactiveVisitorVisaIcon,
};
