# Root sonar-project.properties
sonar.projectKey=digital-transformation-ui
sonar.projectName=WALAA UI Digital Transformation Project
sonar.sources=web-apps/consumer-portal/src,web-apps/corporate-portal/src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/__tests__/**
sonar.javascript.lcov.reportPaths=web-apps/consumer-portal/coverage/lcov.info,web-apps/corporate-portal/coverage/lcov.info