export const mockVehicleDetail = {
  "chassisNumber": "JTMHT09J8B4054633",
  "logId": "70",
  "vehicleColour": "ابيض",
  "manufactureYear": "2011",
  "vehicleOwnerName": "محمد كمال الدين ابوالفتح محمد",
  "vehicleRegistrationCity": null,
  "vehicleLoad": null,
  "vehicleMakeText": "تويوتا",
  "vehicleModelText": "جي اكس  ار",
  "weight": "2300",
  "vehicleOwnerId": null,
  "lkVehBodyType": "5",
  "lkVehicleClassDesc": "سيارة ركـوب",
  "vehicleCapacity": "5663",
  "vehicleMakerCode": "-1",
  "vehicleModelCode": "-1",
  "cylindercapacity": "8",
  "coOwnerFullName": null,
  "coOwnerId": null,
  "plateNo": "6548",
  "plateNoText1": "R-ر",
  "plateNoText2": "N-ن",
  "plateNoText3": "B-ب",
  "plateType": "1",
  "regCityLocationCode": "4546",
  "vehicleRegistrationExpiryDateH": "28-07-1448",
  "transmissionType": "AUTOMATIC",
  "engineCapacity": "5.7 L",
  "referenceNo": "ADME-REF-6825975",
  "admeid": 8958,
  "description": "VXR TOP 5.7 L V8 cyls 362 HP SUV AUTOMATIC 5 DOORS 8 SEATS ALL WHEEL DRIVE - GCC",
  "vehicleValue": 67950,
  "vehicleMaxValue": 89200,
  "vehicleMinValue": 46700,
  "modelYearID": 62,
  "make": "Toyota",
  "makeID": 67,
  "model": "Land Cruiser",
  "modelID": 569,
  "spec": "VXR TOP",
  "specID": 795,
  "engineSizeID": 50,
  "vehicleCylinders": "V8",
  "noOfCylsID": 7,
  "hp": "362 HP",
  "hpID": 323,
  "vehicleBodyType": "SUV",
  "bodyTypeID": 9,
  "transmissionID": 2,
  "doors": "5 DOORS",
  "doorsID": 5,
  "seats": "8 SEATS",
  "seatsID": 8,
  "finalDrive": "ALL WHEEL DRIVE",
  "finalDriveID": 4,
  "vehicleType": "CAR",
  "vehicleTypeID": 1,
  "fuelType": "PETROL",
  "fuelID": 1,
  "engineType": "DUAL VVTI",
  "engineTypeID": 46,
  "axels": "2 AXLES",
  "axelsID": 1,
  "gears": "6 GEARS",
  "gearsID": 5,
  "cubicCapacity": "5663",
  "cubicCapacityID": 83
}
export const mockVehicaleFormResponse = {
    vehicleSequenceNo: "675885110",
    customCardNumber: "4124001474",
    modelYear: "2020",
    ownerId: "2368578205",
}


export const mockPolicyRisk = {
  "vehicleDefinitionType": "1",
  "vehicleSequenceNo": "809601710",
  "vehicleCustomID": "",
  "vehicleMake": "",
  "vehicleMakeText": "فورد",
  "vehicleModel": "",
  "vehicleModelText": "فيوجن",
  "vehicleBodyType": "0",
  "vehicleValue": 37250,
  "deductibleReferenceNo": "",
  "deductibleAmount": 0.0,
  "vehicleCapacity": 0,
  "vehicleCylinders": 0,
  "vehicleRegion": "",
  "vehicleOwnerName": "عمر عبدالمحسن بن احمد  النعيم",
  "vehicleOwnerId": "1080072984",
  "plateType": "1",
  "plateNo": "6302",
  "plateNoText1": "J - ح",
  "plateNoText2": "U - و",
  "plateNoText3": "N - ن",
  "manufactureYear": 2022,
  "vehicleColour": "رمادي",
  "vehicleRegistrationCity": "",
  "chassisNo": "3FA6P0G72GR335317",
  "vehicleRegistrationExpiryDateH": "26-11-1446",
  "depreciationRatePercentage": 0.0,
  "vehicleMileage": 0,
  "expectedMileage": 1,
  "engineCapacity": 0,
  "transmissionType": 1,
  "vehicleParkingType": 1,
  "vehicleAntitheftAlarm": "0",
  "fireExtinguisher": "0",
  "antiLockBrakingSystem": "0",
  "vehicleAutoBraking": "0",
  "vehicleABS": "0",
  "vehicleCruiseControl": "0",
  "vehicleAdaptiveCruiseControl": "0",
  "vehicleRearSensors": "0",
  "vehicleFrontSensors": "0",
  "vehicleRearCamera": "0",
  "vehicleFrontCamera": "0",
  "vehicle360Camera": "0",
  "vehicleUsage": 1,
  "axleWeight": "0",
  "weight": 1454,
  "vehicleModification": "0",
  "remarks": "-",
  "vehicleDriveCity": "",
  "repairCondition": 2,
  "vehicleOwnerTransfer": 0,
  "hasTrailer": 0,
  "yakeenRetrieveFlag": "Y",
  "drivers": [
      {
          "mainDriverInd": "Y",
          "usagePercentage": 1.0,
          "nationality": "Saudi Arabia",
          "driverIDType": 2,
          "driverID": "1080072984",
          "driverName": "OMAR ABDULMOHSEN AHMED ALNAIM",
          "driverNameArabic": "عمر عبدالمحسن بن احمد النعيم",
          "relation": 1,
          "dateOfBirth": "1994-01-04",
          "dateOfBirthH": "22-07-1414",
          "gender": "M",
          "occupation": "OTHERS",
          "educationLevel": 5,
          "maritalStatusCd": 1,
          "childrenBelow16": 0,
          "workCompanyName": "Walaa",
          "workCityCode": "",
          "homeCityCode": "",
          "homeAddress": "",
          "licenseType": 1,
          "licenseYear": 5,
          "licenseExpiryDateH": "26-11-1446",
          "idIssuePlaceCode": "الخبر",
          "ncdFreeYears": 1,
          "ncdReference": "NCD23052462833",
          "noOfAccidents": 0,
          "noOfClaims": 0,
          "unitNo": "",
          "buildingNumber": "2180",
          "streetName": "28جـ",
          "district": "حي الراكة الشمالية",
          "city": "الدمام",
          "additionalNumber": "8822",
          "postalCode": "34225",
          "healthConditions": "",
          "trafficViolations": "",
          "najmCaseDetails": [],
          "validDrivingLicenses": []
      }
  ]
}
