// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
const {
    VITE_BASE_SIGNUP_URL,
    VITE_CONTENT_BASE_URI,
    VITE_BACKEND_BASE_URL,
    VITE_BASE_URL_TRAVEL_QUOTEANDBUY,
    VITE_BACKEND_TRAVEL_QUOTEANDBUY,
    VITE_GOOGLE_MAPS_EMBED_API_KEY,
    VITE_GOOGLE_MAPS_API_KEY,
    VITE_BACKEND_MOTOR_URL,
    VITE_BASE_URL_MOTOR_BUY,
    VITE_BASE_URL_MOTOR_QUOTEANDBUY,
    VITE_BASE_URL_MOTOR_QUOTE_AND_BUY_URL,
    VITE_BASE_URL_MOTOR_ENDORSEMENT_URL,
    VITE_BACKEND_UTILITY_URL,
    VITE_REDIS_UTILITY,
    VITE_POLICY_CANCELLATION_BASE_URL,
    VITE_COMMON_UTILITY_V1_ENDPOINT,
    VITE_HOME_QAB_URL,
    VITE_BASE_LOGIN_URL,
    VITE_BACKEND_TRAVEL_MASTER_DATA_URL,   
    VITE_BASE_CASECREATION_URL,
    VITE_BACKEND_COMMON_UTILITY_URL,
    VITE_BACKEND_COMMON_DASHBOARD_URL,
    VITE_BASE_URL_DASHBOARD_MOTOR,
    VITE_BACKEND_URL,
} = import.meta.env;

const commonTexts = Object.freeze({
  ar: {
    home: "بيت",
    user: "مستخدم",
  },
  en: {
    home: "Home",
    user: "User",
  },
});

const LANGUAGE_ARABIC = "ar";
const LANGUAGE_ENGLISH = "en";
const NOT_APPLICABLE = "N/A"; // when data is not available, null, undefined, empty string `N/A` will be displayed
const CURRENCY_TEXT = "SAR";
const TOAST_AUTOCLOSE_TIMER = 3000; // 3 seconds
const NON_SA_IBAN_LOWER_LIMIT = 16; // Lower limit for non-SA IBAN length
const NON_SA_IBAN_UPPER_LIMIT = 34; // Upper limit for non-SA IBAN length
const SA_IBAN_LENGTH = 24; // Length for SA IBAN
export {
  VITE_CONTENT_BASE_URI,
  VITE_BACKEND_BASE_URL,
  VITE_GOOGLE_MAPS_EMBED_API_KEY,
  VITE_GOOGLE_MAPS_API_KEY,
  VITE_BACKEND_MOTOR_URL,
  VITE_BASE_URL_MOTOR_BUY,
  VITE_BASE_URL_MOTOR_QUOTEANDBUY,
  VITE_BASE_URL_MOTOR_QUOTE_AND_BUY_URL,
  VITE_BASE_URL_MOTOR_ENDORSEMENT_URL,
  VITE_BACKEND_UTILITY_URL,
  VITE_BACKEND_COMMON_UTILITY_URL,
  VITE_BACKEND_COMMON_DASHBOARD_URL,
  VITE_BACKEND_TRAVEL_MASTER_DATA_URL,
  VITE_COMMON_UTILITY_V1_ENDPOINT,
  VITE_HOME_QAB_URL,
  VITE_REDIS_UTILITY,
  VITE_POLICY_CANCELLATION_BASE_URL,
  VITE_BACKEND_TRAVEL_QUOTEANDBUY,
  VITE_BASE_URL_TRAVEL_QUOTEANDBUY,
  VITE_BASE_LOGIN_URL,
  VITE_BASE_SIGNUP_URL,  
  VITE_BASE_URL_DASHBOARD_MOTOR,
  commonTexts,
  LANGUAGE_ARABIC,
  LANGUAGE_ENGLISH,
  NOT_APPLICABLE,
  CURRENCY_TEXT,
  VITE_BASE_CASECREATION_URL,
  TOAST_AUTOCLOSE_TIMER,
  VITE_BACKEND_URL,
  NON_SA_IBAN_LOWER_LIMIT,
  NON_SA_IBAN_UPPER_LIMIT,
  SA_IBAN_LENGTH,
};
